<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE xe-datafeed [
<!ELEMENT xe-datafeed (header*,currency*)>
<!ELEMENT header (hname,hvalue)>
<!ELEMENT hname (#PCDATA)>
<!ELEMENT hvalue (#PCDATA)>
<!ELEMENT currency (csymbol,cname,crate)>
<!ELEMENT csymbol (#PCDATA)>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT crate (#PCDATA)>
]>

<xe-datafeed>
<header><hname>Version</hname><hvalue>2.45</hvalue></header>
<header><hname>Status</hname><hvalue>OK</hvalue></header>
<header><hname>Current UTC Time</hname><hvalue>2011.04.27 06:46:01</hvalue></header>
<header><hname>Notice</hname><hvalue>All use of this data is strictly regulated under the licensing Agreement. Unauthorized use is a breach of your duties and responsibilities under this Agreement.</hvalue></header>
<header><hname>Redistribution</hname><hvalue>REDISTRIBUTION OF CURRENCY DATA PROHIBITED. The license Agreement only permits download of this data directly from xe.com to a single CPU. CURRENCY DATA MAY NOT BE SHARED WITH OTHER CPUs. You may use currency data in calculations involving other non-currency data, and distribute the results, but each CPU requiring currency data on its own requires separate licensing from xe.com. For more information, refer to your copy of the licence agreement or contact us at: dfs@xe.com</hvalue></header>
<header><hname>Licensed Company</hname><hvalue>TMF VAT Services Ltd</hvalue></header>
<header><hname>Designated Contact</hname><hvalue>Aaron Smith</hvalue></header>
<header><hname>Contact E-Mail</hname><hvalue>aaron@cordistechnologies.com</hvalue></header>
<header><hname>Feed Expires on</hname><hvalue>July 26 2011</hvalue></header>
<header><hname>Days Remaining</hname><hvalue>90</hvalue></header>
<header><hname>UTC Time of Your Next Update</hname><hvalue>2011.04.28 00:00:00</hvalue></header>
<header><hname>Seconds Until Your Next Update</hname><hvalue>62039</hvalue></header>
<header><hname>Rate Format</hname><hvalue>XML</hvalue></header>
<header><hname>Rate Type</hname><hvalue>DAILY</hvalue></header>
<header><hname>Permitted accesses per week</hname><hvalue>18</hvalue></header>
<header><hname>Accesses so far this week</hname><hvalue>13</hvalue></header>
<header><hname>Accesses remaining in this week</hname><hvalue>5</hvalue></header>
<header><hname>Days until new access period begins</hname><hvalue>1</hvalue></header>
<header><hname>UTC Timestamp</hname><hvalue>2011.04.27 00:00:00</hvalue></header>
<header><hname>Local Timezone</hname><hvalue>UTC</hvalue></header>
<header><hname>Local Timestamp</hname><hvalue>2011.04.27 00:00:00</hvalue></header>
<header><hname>Base Currency</hname><hvalue>USD</hvalue></header>
<currency><csymbol>AED</csymbol><cname>United Arab Emirates Dirhams</cname><crate>3.6731500626</crate></currency>
<currency><csymbol>AFN</csymbol><cname>Afghanistan Afghanis</cname><crate>42.9850006104</crate></currency>
<currency><csymbol>ALL</csymbol><cname>Albania Leke</cname><crate>96.9700000000</crate></currency>
<currency><csymbol>AMD</csymbol><cname>Armenia Drams</cname><crate>373.5700073242</crate></currency>
<currency><csymbol>ANG</csymbol><cname>Netherlands Antilles Guilders</cname><crate>1.7890000343</crate></currency>
<currency><csymbol>AOA</csymbol><cname>Angola Kwanza</cname><crate>93.0410003662</crate></currency>
<currency><csymbol>ARS</csymbol><cname>Argentina Pesos</cname><crate>4.0789999962</crate></currency>
<currency><csymbol>AUD</csymbol><cname>Australia Dollars</cname><crate>0.9241258252</crate></currency>
<currency><csymbol>AWG</csymbol><cname>Aruba Guilders</cname><crate>1.7900000000</crate></currency>
<currency><csymbol>AZN</csymbol><cname>Azerbaijan New Manats</cname><crate>0.7910000086</crate></currency>
<currency><csymbol>BAM</csymbol><cname>Bosnia and Herzegovina Convertible Marka</cname><crate>1.3301947371</crate></currency>
<currency><csymbol>BBD</csymbol><cname>Barbados Dollars</cname><crate>2.0000000000</crate></currency>
<currency><csymbol>BDT</csymbol><cname>Bangladesh Taka</cname><crate>72.9499969482</crate></currency>
<currency><csymbol>BGN</csymbol><cname>Bulgaria Leva</cname><crate>1.3302336760</crate></currency>
<currency><csymbol>BHD</csymbol><cname>Bahrain Dinars</cname><crate>0.3770449758</crate></currency>
<currency><csymbol>BIF</csymbol><cname>Burundi Francs</cname><crate>1210.0000000000</crate></currency>
<currency><csymbol>BMD</csymbol><cname>Bermuda Dollars</cname><crate>1.0000000000</crate></currency>
<currency><csymbol>BND</csymbol><cname>Brunei Dollars</cname><crate>1.2310696433</crate></currency>
<currency><csymbol>BOB</csymbol><cname>Bolivia Bolivianos</cname><crate>6.9600000381</crate></currency>
<currency><csymbol>BRL</csymbol><cname>Brazil Reais</cname><crate>1.5620000362</crate></currency>
<currency><csymbol>BSD</csymbol><cname>Bahamas Dollars</cname><crate>1.0000000000</crate></currency>
<currency><csymbol>BTN</csymbol><cname>Bhutan Ngultrum</cname><crate>44.4850006104</crate></currency>
<currency><csymbol>BWP</csymbol><cname>Botswana Pulas</cname><crate>6.4683055374</crate></currency>
<currency><csymbol>BYR</csymbol><cname>Belarus Rubles</cname><crate>3045.0000000000</crate></currency>
<currency><csymbol>BZD</csymbol><cname>Belize Dollars</cname><crate>1.9485000372</crate></currency>
<currency><csymbol>CAD</csymbol><cname>Canada Dollars</cname><crate>0.9496013019</crate></currency>
<currency><csymbol>CDF</csymbol><cname>Congo/Kinshasa Francs</cname><crate>905.0000000000</crate></currency>
<currency><csymbol>CHF</csymbol><cname>Switzerland Francs</cname><crate>0.8705030691</crate></currency>
<currency><csymbol>CLP</csymbol><cname>Chile Pesos</cname><crate>462.4500122070</crate></currency>
<currency><csymbol>CNY</csymbol><cname>China Yuan Renminbi</cname><crate>6.5240001678</crate></currency>
<currency><csymbol>COP</csymbol><cname>Colombia Pesos</cname><crate>1782.0000000000</crate></currency>
<currency><csymbol>CRC</csymbol><cname>Costa Rica Colones</cname><crate>496.7000122070</crate></currency>
<currency><csymbol>CUC</csymbol><cname>Cuba Convertible Pesos</cname><crate>1.0000000000</crate></currency>
<currency><csymbol>CUP</csymbol><cname>Cuba Pesos</cname><crate>26.5000000000</crate></currency>
<currency><csymbol>CVE</csymbol><cname>Cape Verde Escudos</cname><crate>75.3499984741</crate></currency>
<currency><csymbol>CZK</csymbol><cname>Czech Republic Koruny</cname><crate>16.3599238953</crate></currency>
<currency><csymbol>DJF</csymbol><cname>Djibouti Francs</cname><crate>174.6999969482</crate></currency>
<currency><csymbol>DKK</csymbol><cname>Denmark Kroner</cname><crate>5.0713754277</crate></currency>
<currency><csymbol>DOP</csymbol><cname>Dominican Republic Pesos</cname><crate>37.7999992371</crate></currency>
<currency><csymbol>DZD</csymbol><cname>Algeria Dinars</cname><crate>71.2050018311</crate></currency>
<currency><csymbol>EEK</csymbol><cname>Estonia Krooni</cname><crate>10.6415578966</crate></currency>
<currency><csymbol>EGP</csymbol><cname>Egypt Pounds</cname><crate>5.9489998817</crate></currency>
<currency><csymbol>ERN</csymbol><cname>Eritrea Nakfa</cname><crate>15.0000000000</crate></currency>
<currency><csymbol>ETB</csymbol><cname>Ethiopia Birr</cname><crate>16.7712001801</crate></currency>
<currency><csymbol>EUR</csymbol><cname>Euro</cname><crate>0.6801177695</crate></currency>
<currency><csymbol>FJD</csymbol><cname>Fiji Dollars</cname><crate>1.7655367496</crate></currency>
<currency><csymbol>FKP</csymbol><cname>Falkland Islands Pounds</cname><crate>0.6057712370</crate></currency>
<currency><csymbol>GBP</csymbol><cname>United Kingdom Pounds</cname><crate>0.6057712370</crate></currency>
<currency><csymbol>GEL</csymbol><cname>Georgia Lari</cname><crate>1.6411999464</crate></currency>
<currency><csymbol>GGP</csymbol><cname>Guernsey Pounds</cname><crate>0.6057712370</crate></currency>
<currency><csymbol>GHS</csymbol><cname>Ghana Cedis</cname><crate>1.4945000410</crate></currency>
<currency><csymbol>GIP</csymbol><cname>Gibraltar Pounds</cname><crate>0.6057712370</crate></currency>
<currency><csymbol>GMD</csymbol><cname>Gambia Dalasi</cname><crate>26.5499992371</crate></currency>
<currency><csymbol>GNF</csymbol><cname>Guinea Francs</cname><crate>7650.0000000000</crate></currency>
<currency><csymbol>GTQ</csymbol><cname>Guatemala Quetzales</cname><crate>7.5980000496</crate></currency>
<currency><csymbol>GYD</csymbol><cname>Guyana Dollars</cname><crate>203.9499969482</crate></currency>
<currency><csymbol>HKD</csymbol><cname>Hong Kong Dollars</cname><crate>7.7716115674</crate></currency>
<currency><csymbol>HNL</csymbol><cname>Honduras Lempiras</cname><crate>18.8950004578</crate></currency>
<currency><csymbol>HRK</csymbol><cname>Croatia Kuna</cname><crate>5.0003261156</crate></currency>
<currency><csymbol>HTG</csymbol><cname>Haiti Gourdes</cname><crate>40.3499984741</crate></currency>
<currency><csymbol>HUF</csymbol><cname>Hungary Forint</cname><crate>180.0438695965</crate></currency>
<currency><csymbol>IDR</csymbol><cname>Indonesia Rupiahs</cname><crate>8650.0000000000</crate></currency>
<currency><csymbol>ILS</csymbol><cname>Israel New Shekels</cname><crate>3.4200332800</crate></currency>
<currency><csymbol>IMP</csymbol><cname>Isle of Man Pounds</cname><crate>0.6057712370</crate></currency>
<currency><csymbol>INR</csymbol><cname>India Rupees</cname><crate>44.4850006104</crate></currency>
<currency><csymbol>IQD</csymbol><cname>Iraq Dinars</cname><crate>1178.5000000000</crate></currency>
<currency><csymbol>IRR</csymbol><cname>Iran Rials</cname><crate>10503.0000000000</crate></currency>
<currency><csymbol>ISK</csymbol><cname>Iceland Kronur</cname><crate>111.9997160955</crate></currency>
<currency><csymbol>JEP</csymbol><cname>Jersey Pounds</cname><crate>0.6057712370</crate></currency>
<currency><csymbol>JMD</csymbol><cname>Jamaica Dollars</cname><crate>84.8000030518</crate></currency>
<currency><csymbol>JOD</csymbol><cname>Jordan Dinars</cname><crate>0.7100000381</crate></currency>
<currency><csymbol>JPY</csymbol><cname>Japan Yen</cname><crate>81.3652790802</crate></currency>
<currency><csymbol>KES</csymbol><cname>Kenya Shillings</cname><crate>83.9000015259</crate></currency>
<currency><csymbol>KGS</csymbol><cname>Kyrgyzstan Soms</cname><crate>46.9049987793</crate></currency>
<currency><csymbol>KHR</csymbol><cname>Cambodia Riels</cname><crate>3985.0000000000</crate></currency>
<currency><csymbol>KMF</csymbol><cname>Comoros Francs</cname><crate>334.5960087850</crate></currency>
<currency><csymbol>KPW</csymbol><cname>North Korea Won</cname><crate>143.0792725253</crate></currency>
<currency><csymbol>KRW</csymbol><cname>South Korea Won</cname><crate>1078.3961370214</crate></currency>
<currency><csymbol>KWD</csymbol><cname>Kuwait Dinars</cname><crate>0.2752950192</crate></currency>
<currency><csymbol>KYD</csymbol><cname>Cayman Islands Dollars</cname><crate>0.8199999928</crate></currency>
<currency><csymbol>KZT</csymbol><cname>Kazakhstan Tenge</cname><crate>145.4499969482</crate></currency>
<currency><csymbol>LAK</csymbol><cname>Laos Kips</cname><crate>8005.0000000000</crate></currency>
<currency><csymbol>LBP</csymbol><cname>Lebanon Pounds</cname><crate>1504.5000000000</crate></currency>
<currency><csymbol>LKR</csymbol><cname>Sri Lanka Rupees</cname><crate>110.1699981689</crate></currency>
<currency><csymbol>LRD</csymbol><cname>Liberia Dollars</cname><crate>71.5000000000</crate></currency>
<currency><csymbol>LSL</csymbol><cname>Lesotho Maloti</cname><crate>6.6729663104</crate></currency>
<currency><csymbol>LTL</csymbol><cname>Lithuania Litai</cname><crate>2.3483106345</crate></currency>
<currency><csymbol>LVL</csymbol><cname>Latvia Lati</cname><crate>0.4823303806</crate></currency>
<currency><csymbol>LYD</csymbol><cname>Libya Dinars</cname><crate>1.1956999307</crate></currency>
<currency><csymbol>MAD</csymbol><cname>Morocco Dirhams</cname><crate>7.7353000641</crate></currency>
<currency><csymbol>MDL</csymbol><cname>Moldova Lei</cname><crate>11.5299997330</crate></currency>
<currency><csymbol>MGA</csymbol><cname>Madagascar Ariary</cname><crate>1960.0000000000</crate></currency>
<currency><csymbol>MKD</csymbol><cname>Macedonia Denars</cname><crate>42.0000000000</crate></currency>
<currency><csymbol>MMK</csymbol><cname>Myanmar Kyats</cname><crate>6.4099998474</crate></currency>
<currency><csymbol>MNT</csymbol><cname>Mongolia Tugriks</cname><crate>1247.5000000000</crate></currency>
<currency><csymbol>MOP</csymbol><cname>Macau Patacas</cname><crate>8.0047599144</crate></currency>
<currency><csymbol>MRO</csymbol><cname>Mauritania Ouguiyas</cname><crate>272.5000000000</crate></currency>
<currency><csymbol>MUR</csymbol><cname>Mauritius Rupees</cname><crate>27.2999992371</crate></currency>
<currency><csymbol>MVR</csymbol><cname>Maldives Rufiyaa</cname><crate>12.8000000000</crate></currency>
<currency><csymbol>MWK</csymbol><cname>Malawi Kwachas</cname><crate>150.0000000000</crate></currency>
<currency><csymbol>MXN</csymbol><cname>Mexico Pesos</cname><crate>11.5668260027</crate></currency>
<currency><csymbol>MYR</csymbol><cname>Malaysia Ringgits</cname><crate>2.9842000008</crate></currency>
<currency><csymbol>MZN</csymbol><cname>Mozambique Meticais</cname><crate>31.0000000000</crate></currency>
<currency><csymbol>NAD</csymbol><cname>Namibia Dollars</cname><crate>6.6729663104</crate></currency>
<currency><csymbol>NGN</csymbol><cname>Nigeria Nairas</cname><crate>154.6300048828</crate></currency>
<currency><csymbol>NIO</csymbol><cname>Nicaragua Cordobas</cname><crate>22.2250003815</crate></currency>
<currency><csymbol>NOK</csymbol><cname>Norway Kroner</cname><crate>5.2952901770</crate></currency>
<currency><csymbol>NPR</csymbol><cname>Nepal Rupees</cname><crate>71.3000030518</crate></currency>
<currency><csymbol>NZD</csymbol><cname>New Zealand Dollars</cname><crate>1.2366424862</crate></currency>
<currency><csymbol>OMR</csymbol><cname>Oman Rials</cname><crate>0.3850499988</crate></currency>
<currency><csymbol>PAB</csymbol><cname>Panama Balboas</cname><crate>1.0000000000</crate></currency>
<currency><csymbol>PEN</csymbol><cname>Peru Nuevos Soles</cname><crate>2.8269999027</crate></currency>
<currency><csymbol>PGK</csymbol><cname>Papua New Guinea Kina</cname><crate>2.4783148031</crate></currency>
<currency><csymbol>PHP</csymbol><cname>Philippines Pesos</cname><crate>43.2799987793</crate></currency>
<currency><csymbol>PKR</csymbol><cname>Pakistan Rupees</cname><crate>84.6600036621</crate></currency>
<currency><csymbol>PLN</csymbol><cname>Poland Zlotych</cname><crate>2.6797118483</crate></currency>
<currency><csymbol>PYG</csymbol><cname>Paraguay Guarani</cname><crate>3900.0000000000</crate></currency>
<currency><csymbol>QAR</csymbol><cname>Qatar Riyals</cname><crate>3.6419501305</crate></currency>
<currency><csymbol>RON</csymbol><cname>Romania New Lei</cname><crate>2.7686081676</crate></currency>
<currency><csymbol>RSD</csymbol><cname>Serbia Dinars</cname><crate>69.1262969971</crate></currency>
<currency><csymbol>RUB</csymbol><cname>Russia Rubles</cname><crate>27.7725455634</crate></currency>
<currency><csymbol>RWF</csymbol><cname>Rwanda Francs</cname><crate>592.0000000000</crate></currency>
<currency><csymbol>SAR</csymbol><cname>Saudi Arabia Riyals</cname><crate>3.7501649738</crate></currency>
<currency><csymbol>SBD</csymbol><cname>Solomon Islands Dollars</cname><crate>7.5323253746</crate></currency>
<currency><csymbol>SCR</csymbol><cname>Seychelles Rupees</cname><crate>12.0249996185</crate></currency>
<currency><csymbol>SDG</csymbol><cname>Sudan Pounds</cname><crate>2.6714999676</crate></currency>
<currency><csymbol>SEK</csymbol><cname>Sweden Kronor</cname><crate>6.0822751387</crate></currency>
<currency><csymbol>SGD</csymbol><cname>Singapore Dollars</cname><crate>1.2310696433</crate></currency>
<currency><csymbol>SHP</csymbol><cname>Saint Helena Pounds</cname><crate>0.6057712370</crate></currency>
<currency><csymbol>SLL</csymbol><cname>Sierra Leone Leones</cname><crate>4355.0000000000</crate></currency>
<currency><csymbol>SOS</csymbol><cname>Somalia Shillings</cname><crate>1600.0000000000</crate></currency>
<currency><csymbol>SPL</csymbol><cname>Seborga Luigini</cname><crate>0.1666666667</crate></currency>
<currency><csymbol>SRD</csymbol><cname>Suriname Dollars</cname><crate>3.2500000000</crate></currency>
<currency><csymbol>STD</csymbol><cname>S?o Tome and Principe Dobras</cname><crate>16968.0000000000</crate></currency>
<currency><csymbol>SVC</csymbol><cname>El Salvador Colones</cname><crate>8.7500000000</crate></currency>
<currency><csymbol>SYP</csymbol><cname>Syria Pounds</cname><crate>47.4500007629</crate></currency>
<currency><csymbol>SZL</csymbol><cname>Swaziland Emalangeni</cname><crate>6.6729663104</crate></currency>
<currency><csymbol>THB</csymbol><cname>Thailand Baht</cname><crate>29.9399365249</crate></currency>
<currency><csymbol>TJS</csymbol><cname>Tajikistan Somoni</cname><crate>4.4650998116</crate></currency>
<currency><csymbol>TMM</csymbol><cname>Turkmenistan Manats</cname><crate>14250.0000000000</crate></currency>
<currency><csymbol>TMT</csymbol><cname>Turkmenistan New Manats</cname><crate>2.8500000000</crate></currency>
<currency><csymbol>TND</csymbol><cname>Tunisia Dinars</cname><crate>1.3550000162</crate></currency>
<currency><csymbol>TOP</csymbol><cname>Tonga Pa'anga</cname><crate>1.7927572769</crate></currency>
<currency><csymbol>TRY</csymbol><cname>Turkey Lira</cname><crate>1.5206027440</crate></currency>
<currency><csymbol>TTD</csymbol><cname>Trinidad and Tobago Dollars</cname><crate>6.3299999237</crate></currency>
<currency><csymbol>TVD</csymbol><cname>Tuvalu Dollars</cname><crate>0.9241258252</crate></currency>
<currency><csymbol>TWD</csymbol><cname>Taiwan New Dollars</cname><crate>28.8950004578</crate></currency>
<currency><csymbol>TZS</csymbol><cname>Tanzania Shillings</cname><crate>1507.5000000000</crate></currency>
<currency><csymbol>UAH</csymbol><cname>Ukraine Hryvnia</cname><crate>7.9675002098</crate></currency>
<currency><csymbol>UGX</csymbol><cname>Uganda Shillings</cname><crate>2370.0000000000</crate></currency>
<currency><csymbol>USD</csymbol><cname>United States Dollars</cname><crate>1.0000000000</crate></currency>
<currency><csymbol>UYU</csymbol><cname>Uruguay Pesos</cname><crate>18.7500000000</crate></currency>
<currency><csymbol>UZS</csymbol><cname>Uzbekistan Sums</cname><crate>1703.0000000000</crate></currency>
<currency><csymbol>VEB</csymbol><cname>Venezuela Bolivares</cname><crate>4300.0000000000</crate></currency>
<currency><csymbol>VEF</csymbol><cname>Venezuela Bolivares Fuertes</cname><crate>4.3000000000</crate></currency>
<currency><csymbol>VND</csymbol><cname>Vietnam Dong</cname><crate>20680.0000000000</crate></currency>
<currency><csymbol>VUV</csymbol><cname>Vanuatu Vatu</cname><crate>90.5599975586</crate></currency>
<currency><csymbol>WST</csymbol><cname>Samoa Tala</cname><crate>2.2642363699</crate></currency>
<currency><csymbol>XAF</csymbol><cname>Communaut? Financi?re Africaine Francs BEAC</cname><crate>446.1280117133</crate></currency>
<currency><csymbol>XAG</csymbol><cname>Silver Ounces</cname><crate>0.0216623795</crate></currency>
<currency><csymbol>XAU</csymbol><cname>Gold Ounces</cname><crate>0.0006624382</crate></currency>
<currency><csymbol>XCD</csymbol><cname>East Caribbean Dollars</cname><crate>2.7000000477</crate></currency>
<currency><csymbol>XDR</csymbol><cname>International Monetary Fund Special Drawing Rights</cname><crate>0.6212909818</crate></currency>
<currency><csymbol>XOF</csymbol><cname>Communaut? Financi?re Africaine Francs BCEAO</cname><crate>446.1280117133</crate></currency>
<currency><csymbol>XPD</csymbol><cname>Palladium Ounces</cname><crate>0.0013213134</crate></currency>
<currency><csymbol>XPF</csymbol><cname>Comptoirs Fran?ais du Pacifique Francs</cname><crate>81.1596383625</crate></currency>
<currency><csymbol>XPT</csymbol><cname>Platinum Ounces</cname><crate>0.0005522544</crate></currency>
<currency><csymbol>YER</csymbol><cname>Yemen Rials</cname><crate>215.0000000000</crate></currency>
<currency><csymbol>ZAR</csymbol><cname>South Africa Rand</cname><crate>6.6729663104</crate></currency>
<currency><csymbol>ZMK</csymbol><cname>Zambia Kwacha</cname><crate>4720.0000000000</crate></currency>
<currency><csymbol>ZWD</csymbol><cname>Zimbabwe Dollars</cname><crate>361.9000000000</crate></currency>
</xe-datafeed>